import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    { type: 'doc', id: 'README' },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/schema-definition',
        'guides/encoding-and-decoding',
        'guides/custom-data-type',
        'guides/tips-and-tricks',
      ],
    },
    {
      type: 'doc',
      label: 'Examples',
      id: 'examples',
    },
    {
      type: 'doc',
      label: 'Benchmark',
      id: 'benchmark',
    },
    // { type: 'autogenerated', dirName: 'tutorial-extras' },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      items: require('./docs/api/typedoc-sidebar.cjs')
      // items: [{ type: 'autogenerated', dirName: 'api' }]
    }
  ],
};

export default sidebars;
