name: Byteform CI

on:
  push:
    branches:
      - main # Run this workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Run this workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4 
      - name: Enable Corepack
        run: corepack enable

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Use the latest LTS version of Node.js
          cache: 'yarn'        # Cache Yarn dependencies

      # Install project dependencies
      - name: Install dependencies
        run: yarn install

      # Run tests to ensure code quality
      - name: Run tests
        run: yarn test

      # Generate code
      - name: Build project
        run: yarn build
